#!/bin/tcsh -f
# add 'x' to '-ef' to trace code as it is executed

##### GO_FS1 - The "Easy" button #####
##### Usage: GO_FS <subjects directory name>
##### Feeds multiple subjects into autorecon1
##### Requires that original scan data be placed in $SUBJECTS_DIR/_orig_
##### 	(Place each subject's anat series in separate folders)



if ( $#argv == 0 ) then
	echo "Usage: $0 <subject dir> <additional params to pass to auto-recon> "
	exit 1
endif

echo "\n <><><><><><><><><><><>< GO FreeSurfer! ><><><><><><><><><><><> \n"


### Check if subjects directory specified ###
if ( "$1" != "" ) then
  set subjdir = $1
else
  echo "\n ERROR: No subjects directory specified \n"
  exit 1
endif

### Set FREESURFER_HOME and SUBJECTS_DIR ###

#source fshome.csh

if ( -e $SUBJECTS_DIR/$subjdir) then
  setenv SUBJECTS_DIR $SUBJECTS_DIR/$subjdir
else
  echo "\n ERROR: Specified subjects directory does not exist \n"
  exit 1
endif

### Check if original scan data exists ###

if ( ! -e $SUBJECTS_DIR/_orig_ ) then
  echo "\n ERROR: Original scan data not found. \n"
  exit 1
endif

### disable functional tools ###

setenv NO_FSFAST

##### (To enable functional tools, disable the above line, enable the following:)
##### (HAVE NOT TESTED THIS YET) (MAYBE BETTER IF NO_FSFAST ANYWAYS)
#setenv FUNCTIONALS_DIR $FREESURFER_HOME/sessions
#	echo "FUNCTIONALS_DIR = $FUNCTIONALS_DIR"
##### (and add the following to ~/matlab/startup.m)
#fsfasthome = getenv('FSFAST_HOME');
#fsfasttoolbox = sprintf('%s/toolbox',fsfasthome');
#path(path,fsfasttoolbox);

### Set up FreeSurfer ###

setenv prompt
source $FREESURFER_HOME/FreeSurferEnv.csh
echo ""











### List out directories in _orig_ , set subj array, prompt to continue ###

echo "Found the following subjects: \n"

set i = 0
set subjID

foreach d ($SUBJECTS_DIR/_orig_/*)
  @ i++
  set subjID = ($subjID $d:t)
  echo "   Subject "$i": " $subjID[$i]
end
set subjCount = $i

set response
while ($response != "n" && $response != "y")
  echo -n "\n Process these $subjCount subjects? [y/n] > "
  set response = $<
end
if ($response == "n") then
  echo "\n Program ended by user \n"
  exit 1
endif




### Prompt user for First Anat Filename's ### 

set firstAnatSame
set stripName
set commonName
set subjNames
set newanat

while ($firstAnatSame != "y" && $firstAnatSame != "n")
  echo -n "\n Are all the anat series named identically? [y/n]: > "
  set firstAnatSame = $<
end

switch ($firstAnatSame)
	case [y]:
		echo -n "\n Please enter the first filename (inc. ext) for all anat series: > "
		set commonName = $<
		breaksw
	case [n]:
		echo "\n Auto detect first file for the anat series:"
		while ($stripName != "y" && $stripName != "n")
		  echo -n "\n Are the subjects listed above their exact serie name? [y/n]: > "
		  set stripName = $<
		end
endsw

set i = 0
while ($i < $subjCount)
	@ i++
    echo -n "    "$subjID[$i]": > "
    if ($firstAnatSame == "y") then
		$newanat = $commonName
    else
		switch($stripName)
			case [n]:
				set newanat = `echo $subjID[$i] | sed 's/\([A-Z]*\)[A-Z].*$/\1/'`
				breaksw
			case [y]:
				set newanat = $subjID[$i]
		endsw
	endif
      set newanat = `echo ${newanat}_0.dcm`
      echo $newanat
      set subjNames = ($subjNames $newanat)	
end



### Run autorecon1 for each subject ###

cd $SUBJECTS_DIR

if ($#argv > 1) then
	set nargs = $argv[2-$#argv]
else
	set nargs = ""
endif

set i = 0
set j = 0
#keep track of concurrent instances for multiprocessing
set instNum = 0


while ($i < $subjCount)
	@ i++
	echo $subjID[$i]
end

while ($instNum < $subjCount)
	echo "\n<><><><><><><><><><><><| START FS PROCESSING > |><><><><><><><><><><><>\n"
	echo "Elapsed $j seconds"
	echo "Instance Num $instNum/$subjCount"
	echo "\n<><> Current jobs <><>\n"	
	ps auwx | awk '{print $1,$13, $14, $15}' | grep /bin/recon-all | sort | uniq
	set i = `ps auwx | awk '{print $1,$13, $14, $15}' | grep /bin/recon-all | sort | uniq | wc -l `
	echo "$i jobs"

	if ($i < 8) then
		@ instNum++	
		echo "\n<><><><><><><><><><><><| NOW PROCESSING <"$subjID[$i]" ($instNum/$subjCount) > |><><><><><><><><><><><>\n"
		gnome-terminal -x tcsh -c "recon-all -i $SUBJECTS_DIR/_orig_/$subjID[$instNum]/$subjNames[$instNum] -all -s $subjID[$instNum] $nargs; sleep 10" &
	endif
	sleep 1	
	@ j++
end




echo ""
date +"Finished $0 without error at %T on %a %b %d %Y"
echo ""
exit 0











#######################
### Simple working loop
#set i = 0
#while ($i < 10)
#	echo $i
#	@ i++
#end
#######################




#############
### TO DO ###
#############
# why don't env's remain 'set' after running this? (they do after running SetUpFreeSurfer.csh or FreeSurferEnv.csh)
# why can't FS_FAST be set up?
