#!/bin/tcsh -ef
if ( $# < 3 ) then
	echo "Usage: Cmd <tbss4 FA frac> <design1 #> <design2 #>"
	exit
endif

tbss_1_preproc *.nii.gz
tbss_2_reg -T
tbss_3_postreg -S
tbss_4_prestats $1
cd stats
design_ttest2 design $2 $3
randomize -i all_FA_skeletonised -o tbss -m mean_FA_skeleton_mask -d design.mat -t design.con -n 500 --T2 -V
fi
