#!/bin/tcsh -ef
if ($# < 1) then
	echo "arg order: dwi label# fa frac radius minlen step_size tensor_file seed_file <density>"  
	exit 1
endif

if( $# == 9) then
    echo "seedTend2Points.py -i $9 -r -n 20"
	seedTend2Points.py -i $9 -r -n 20
endif

if( $# == 10) then
    seedTend2Points.py -i $9 -r -n $10
endif

set seed="$2"
set fiberFile="xst/${seed}.vtk"

if ( ! -d xst ) then
	mkdir xst
endif
# -wspo outputs fibers in world space, unstable results with different space orientation headers!
# use ijk native space instead, apply transform manually!

echo "tend2 fiber -i $1 -dwi -wspos -ns seeds/IC"$seed".txt -o "$fiberFile" -ap \
 -t 2evec0 -stop aniso:cl1,$3 frac:$4 radius:$5 minlen:$6 -n rk4 \
 -k cubic:0.0,0.5 \
 -v 2 -step $7 "
 
tend2 fiber -i $1 -dwi -wspo -ns seeds/IC"$seed".txt -o "$fiberFile" -ap \
 -t 2evec0 -stop aniso:cl2,$3 frac:$4 radius:$5 minlen:$6 -n rk4 \
 -k cubic:0.0,0.5 \
 -v 2 -step $7 
 
echo "copy Scalars"
copyTensors.py -t "$8" -f "$fiberFile" -o "$fiberFile"
#copyScalarsToVtk.py -i "$fiberFile" -m "$8" -o "$fiberFile"

