#!/usr/bin/python

import sys

if len(sys.argv) < 2:
	print 'Usage: %s <filename>'%sys.argv[0]
	sys.exit(0)	

filenames = sys.argv[1:]

for filename in filenames:
	content = []
	f = open(filename, 'r')
	nmax = 0
	for line in f:
		text = line.strip()
		tokens = text.split()
		tlen = len(tokens)
		if tlen > nmax:
			nmax = tlen
		content.append(tokens)


	for i in range(0,nmax):
		for j in content:
			try:
				print j[i],
				print ' ',
			except Exception:
				print ' ',
		print '\n',
	f.close()
